<a href="https://colab.research.google.com/github/drtamakloe/hello-world/blob/master/Q_learning_problem_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# Define the states
location_to_state = {
    'L1' : 0,
    'L2' : 1,
    'L3' : 2,
    'L4' : 3,
    'L5' : 4,
    'L6' : 5,
    'L7' : 6,
    }

# Define the actions
actions = [0,1,2,3,4,5,6]

#import numpy
import numpy as np 
  
#define the rewards matrix
rewards = np.array([[0,0,0,1,0,0,0],
                   [0,0,0,0,3,0,0],
                   [0,0,0,0,0,3,0],
                   [3,0,0,0,1,0,167],
                   [0,1,0,3,0,2,125],
                   [0,0,2,0,1,0,100],
                   [0,0,0,5,3,3,0]])
  
# Maps indices to locations
state_to_location = dict((state,location) for location,state in location_to_state.items())

# Initialize parameters
gamma = 0.9 # Discount factor 
alpha = 1 # Learning rate

def get_optimal_route(start_location,end_location):
    # Copy the rewards matrix to new Matrix
    rewards_new = np.copy(rewards)
    
    # Get the ending state corresponding to the ending location as given
    ending_state = location_to_state[end_location]
    
    # With the above information automatically set the priority of  
    # the given ending state to the highest one
    rewards_new[ending_state,ending_state] = 999

    # -----------Q-Learning algorithm-----------
   
    # Initializing Q-Values
    Q = np.array(np.zeros([7,7]))
    print("Initialized Q matrix")
    print(Q)
  
    

    # Q-Learning process
    for i in range(10000):
        # Pick up a state randomly
        current_state = np.random.randint(0,7) # Python excludes the upper bound
        
        # For traversing through the neighbor locations in the maze
        playable_actions = []
        
        # Iterate through the new rewards matrix and get the actions > 0
        for j in range(7):
            if rewards_new[current_state,j] > 0:
                playable_actions.append(j)
        
        # Pick an action randomly from the list of playable actions  
        # leading us to the next state
        next_state = np.random.choice(playable_actions)
        
        # Compute the temporal difference
        # The action here exactly refers to going to the next state
        TD = rewards_new[current_state,next_state] + gamma * Q[next_state,                         np.argmax(Q[next_state,])] - Q[current_state,next_state]
        
        # Update the Q-Value using the Bellman equation
        Q[current_state,next_state] += alpha * TD

    # Initialize the optimal route with the starting location
    route = [start_location]
    # We do not know about the next location yet, so initialize with the value of 
    # starting location
    next_location = start_location
    
    # We don't know about the exact number of iterations
    # needed to reach to the final location hence while loop will be a good choice 
    # for iteratiing
    
    while(next_location != end_location):
        # Fetch the starting state
        starting_state = location_to_state[start_location]
        
        # Fetch the highest Q-value pertaining to starting state
        next_state = np.argmax(Q[starting_state,])
        
        # We got the index of the next state. But we need the corresponding letter. 
        next_location = state_to_location[next_state]
        route.append(next_location)
        
        # Update the starting location for the next iteration
        start_location = next_location
        print("Trained Q matrix")
        matrix = Q / np.max(Q) * 100
        print(matrix)
        print("Optimal route")
    
    return route


    
print(get_optimal_route('L1', 'L7'))
      
  

Initialized Q matrix
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Trained Q matrix
[[  0.           0.           0.          82.51451451   0.
    0.           0.        ]
 [  0.           0.           0.           0.          82.15615616
    0.           0.        ]
 [  0.           0.           0.           0.           0.
   81.93093093   0.        ]
 [ 74.29309309   0.           0.           0.          82.13613614
    0.          91.67167167]
 [  0.          73.95055055   0.          82.53453453   0.
   81.92092092  91.25125125]
 [  0.           0.          73.75785786   0.          82.13613614
    0.          91.001001  ]
 [  0.           0.           0.          82.55455455  82.15615616
   81.93093093 100.        ]]
Optimal route
Trained Q matrix
[[  0.           0.           0.          82.51451451   0.
    0.           0.        ]
 [  0.           0.      